### ISSUE TITLE
Clear authentication bug

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress-pro-gdrive#37]
Fatal error on clearing authentication. Need to reproduce locally, but having some issues still with the licence expire bug

**Comment by owaincuvelier** [comment]
Update: So it white screens but there's no fatal errors in my log. 

This is the URL ```http://hmbase.dev/wordpress/wp-admin/admin-post.php?action=gdrive_unauth&gdrive-unauth-nonce=26823277c4```

**Comment by pdewouters** [comment]
@owaincuvelier yes I found the issue, will fix today
