### ISSUE TITLE
Update notices are broken

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress-pro-gdrive#39]
Owain reported that most users weren't getting notified about plugin updates for addons.
Turns out the plugin was not sending requests to update server. Also, there is a new version of the plugin updater class.
I have a fix nearly ready to go, just pending a support request I made to EDD.
After that, we'll need to send an email to customers with a link to download the latest version. We can extract the list of active license users from the `Licenses` tab under Downloads on bwp.hmn.md

**Comment by pdewouters** [comment]
Issue is fixed. 
- [ ] send latest version by email

**Comment by owaincuvelier** [comment]
this should be resolved now.
