### ISSUE TITLE
Unable to authenticate with no errors apparent

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress-pro-gdrive#48]
I'm unsure if this is related to the ongoing timing out issue we have going on or not, but this is a new purchaser of the MultiSite license. 

I enabled Query Monitor and there were no large errors, nothing major that stood out. I enabled the php info plugin and saw no missing basic parameters for cURL and functions all look to be okay as well. (I kept both plugins installed but deactivated so that I could use them again if needed)

This user's backups complete fine without the GDrive plugin enabled, but he gets a persistent message when attempting to activate/authenticate the license: 

```Your BackUpWordPress To Google Drive license is invalid, please double check it now to continue to receive updates and support. Thanks!```

Just in case there was a glitch in the license itself, I generated a new licence key for this purchase and tried the new one ... no dice. It doesn't even try to authenticate for more than a few seconds before reloading the page. 

I checked other plugins and nothing stood out as a specific potential for conflict. Here's a copy/paste of all plugins in case one stands out to others: 

```array ( 0 => 'amp/amp.php', 1 => 'backupwordpress-pro-gdrive/backupwordpress-pro-gdrive.php', 2 => 'backupwordpress/backupwordpress.php', 3 => 'broken-link-checker/broken-link-checker.php', 4 => 'cdn-enabler/cdn-enabler.php', 5 => 'disqus-comment-system/disqus.php', 6 => 'glue-for-yoast-seo-amp/yoastseo-amp.php', 7 => 'google-tag-manager/google-tag-manager.php', 8 => 'image-watermark/image-watermark.php', 9 => 'infogram/infogram.php', 10 => 'metronet-profile-picture/metronet-profile-picture.php', 11 => 'optimus/optimus.php', 12 => 'quick-pagepost-redirect-plugin/page_post_redirect_plugin.php', 13 => 'regenerate-thumbnails/regenerate-thumbnails.php', 14 => 'remove-pingback-trackback-comments/remove-pingback-trackback-comments.php', 15 => 'sumome/sumome.php', 16 => 'wordpress-seo/wp-seo.php', 17 => 'wp-contentools/wp-contentools.php', 18 => 'wp-user-avatars/wp-user-avatars.php', )```

Intercom ticket here: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/7167241015
Login info for site included in last few messages. 

Potentially related to the timing out issues we've seen reported: https://github.com/humanmade/backupwordpress/issues/1139

Or maybe the continual license check? https://github.com/humanmade/backupwordpress/issues/1109

**Comment by sambulance** [comment]
@katmoody Hmm, not sure about this one. Please can you try with a single site license? I'm wondering if there's an issue with the license check when there's a comma in the title.

**Comment by katmoody** [comment]
@sambulance - creating a new single license worked!! You might be on to something. But why would the comma make a difference? Can I just update the title and will that work?

**Comment by katmoody** [comment]
Just another update - I took the comma out of the Drive multi-site title and updated it. No difference on trying to activate that license - it still didn't work.

**Comment by katmoody** [comment]
And one last update - I created a brand new Drive Multi-site product and licensed that - that one didn't work either.

**Comment by katmoody** [comment]
I've also put in a general support ticket with EDD to see if there are specific places we could be looking at more clearly on this one, or if others have had similar issues. I really have no idea what else to check now. :(

**Comment by katmoody** [comment]
First response from EDD: 

```
When attempting to activate that license I am seeing an "item_name_mismatch" error. That means the name of the product included in the activation request does not match the name of the product inside of WordPress.

According to this plugin file, the product name is "BackUpWordPress To Google Drive".

Can you confirm that is exactly what it is inside of Easy Digital Downloads too?
```

When running the Query Monitor and checking the debug log, though, I don't see that error so I'm not positive where they're seeing it? I am, however seeing a different error this time around (it's a warning): 

```
[12-Dec-2016 23:36:49 UTC] PHP Notice:  Undefined index: license_key in /home/katsmed1/public_html/bwp/wp-content/plugins/backupwordpress-pro-gdrive/vendor/humanmade/bwp-common/CheckLicense.php on line 176
```

Not sure if that is helpful as well or not. I'm pretty sure this is related to the creation of the product for Multiple site licenses, but I can't help but wonder if this is also creating further issues with our other problems with authentication and activation. 

@sambulance I know you're a rockstar and busy as can be - I'm wondering if it would be prudent to get another opinion from like @pdewouters or @willmot? With the constellation of associated issues, I can't help but think they're related.

**Comment by pdewouters** [comment]
this string https://github.com/humanmade/backupwordpress-pro-gdrive/blob/master/inc/Config.php#L7 must match the product name in the download post

**Comment by katmoody** [comment]
@pdewouters I saw that - but if I am using the same GDrive product name that we used in the original single site license, only for the multiple site license, I'm a little confused if it just pulls the name/title of the post as the product name or does it pull it from somewhere else? I thought it was the product actually attached to the post (I'm confusing myself - I thought it was the actual file download attached, but I guess that was wrong)?

**Comment by pdewouters** [comment]
no, it's not the attachment filename, there is a field for the product name IIRC, and the actual post title as well I think

**Comment by katmoody** [comment]
Okay I don't see a separate field for the product name within the post editor, unless it's a custom field? 

The one difference I DID see what in the source file description, but I have no idea how that would be changed? 

**Single License**
![gdrive-single](https://cloud.githubusercontent.com/assets/5481211/21144506/f51aeda4-c118-11e6-8986-94ff01e177f8.png)

**Multi License**
![gdrive-multi](https://cloud.githubusercontent.com/assets/5481211/21144545/1addf1f8-c119-11e6-87fa-d5013745cbc5.png)

**Comment by katmoody** [comment]
I might have found the issue - the new download had the default name on it (taken from the name of the file) instead of the title used 'officially' ... I removed the download, then re-attached the edited version of that upload (with the edited title). So they now look the same there. Not sure if there is a cache or something that needs purged for that? @pdewouters

**Comment by katmoody** [comment]
Got another response from EDD with a little more information and something to try, but will need feedback and implementation from one of you smart folks ;-) Pippin replied to my last message ... 

> Looks like you have multiple product versions for the same plugin. One product for each license level. Is that correct?
> 
> If so, you should be able to resolve the issue by adding this to your wp-config.php file: 
> 
> `define( 'EDD_BYPASS_NAME_CHECK', true );`

Sound doable and like it would fix the issue @pdewouters or @sambulance?

**Comment by katmoody** [comment]
I've gone ahead and done a commit and PR to see if this constant in the wp-config file will help this specific licensing issue we've run into on the new pricing tier products. :( Will report back when I know more

**Comment by katmoody** [comment]
This specific issue WAS solved with the addition of the constant from EDD in the wp-config file. So I'm closing this one now! :D
